spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.179.16/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
